<style type="text/css">
dt { font-weight: bold; }
</style>
<dt>Customer ID</dt>
<dd><?php echo $this->customer->customer_id; ?></dd>
<dt>Company Name</dt>
<dd><?php echo $this->customer->company; ?></dd>
<dt>Address</dt>
<dd><?php echo $this->customer->address; ?><br /><?php echo $this->customer->address_2 ?></dd>
<dt>City</dt>
<dd><?php echo $this->customer->city; ?></dd>
<dt>State</dt>
<dd><?php echo $this->customer->state; ?></dd>
<dt>ZIP Code</dt>
<dd><?php echo $this->customer->zip; ?></dd>
<dt>Country</dt>
<dd><?php echo $this->customer->country; ?></dd>
<dt>Phone</dt>
<dd><?php echo $this->customer->phone; ?></dd>
<dt>Fax</dt>
<dd><?php echo $this->customer->fax; ?></dd>