<?php $currency = new Zend_Currency(); ?>
<style type="text/css">
dt { font-weight: bold; }
</style>
<dt>Product ID</dt>
<dd><?php echo $this->product->product_id; ?></dd>
<dt>Product Name</dt>
<dd><?php echo $this->product->name; ?></dd>
<dt>Description</dt>
<dd><?php echo $this->product->description; ?></dd>
<dt>Unit Price</dt>
<dd><?php echo $currency->setValue($this->product->unit_price); ?></dd>