<?php
echo $this->doctype('HTML5')?>
<html>
<head>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.10/jquery-ui.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.10.custom.css" />
</head>
<body>
<?php
echo $this->layout()->content?>
</body>
</html>